### PR TITLE
Added two missing actions

### PR DESCRIPTION
**Pull request by lm-ydubler**

### CODE REVIEW

**Review by lm-ydubler — COMMENTED** [review]
Good

**Review by cognifloyd — APPROVED** [review]

**Comment by lm-ydubler** [comment]
@cognifloyd Hi Jacob, hope all has been going well for you and thanks for approving those changes. I can't merge these changes because I'm not an authorized user. When you get a chance - no rush - can you please make me an authorized user so I can merge this PR? Thank you!

**Comment by cognifloyd** [comment]
Hmm. How about now?

**Comment by lm-ydubler** [comment]
Haha, yup! Works now. Thank you.

**Pull request merged**
